In [2]:
import numpy as np

# Lista normal de Python
lista = [1, 2, 3, 4, 5]

# Array de NumPy
array = np.array([1, 2, 3, 4, 5])

print("Lista:", lista)
print("Array:", array)
print("Tipo lista:", type(lista))
print("Tipo array:", type(array))

Lista: [1, 2, 3, 4, 5]
Array: [1 2 3 4 5]
Tipo lista: <class 'list'>
Tipo array: <class 'numpy.ndarray'>


In [3]:
# Intenta multiplicar todos los elementos por 2

lista = [1, 2, 3, 4, 5]
array = np.array([1, 2, 3, 4, 5])

print("Lista x2:", lista * 2)
print("Array x2:", array * 2)

Lista x2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array x2: [ 2  4  6  8 10]


In [4]:
# Con listas necesitas un for
lista_resultado = [x * 2 for x in lista]

# Con NumPy es directo
array_resultado = array * 2

# Y puedes hacer operaciones más complejas igual de fácil
print("Suma:", array + 10)
print("Potencia:", array ** 2)
print("Raíz:", np.sqrt(array))
print("Multiplicar dos arrays:", array * np.array([10, 20, 30, 40, 50]))

Suma: [11 12 13 14 15]
Potencia: [ 1  4  9 16 25]
Raíz: [1.         1.41421356 1.73205081 2.         2.23606798]
Multiplicar dos arrays: [ 10  40  90 160 250]


In [5]:
arr = np.array([10, 20, 30, 40, 50])

# Acceder a un elemento (igual que listas)
print("Primero:", arr[0])
print("Último:", arr[-1])
print("Tercero:", arr[2])

# Slicing — obtener un rango
print("Primeros 3:", arr[0:3])
print("Desde el 2do:", arr[2:])
print("Los últimos 2:", arr[-2:])

Primero: 10
Último: 50
Tercero: 30
Primeros 3: [10 20 30]
Desde el 2do: [30 40 50]
Los últimos 2: [40 50]


In [6]:
# Array 2D (matriz)
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matriz)
print("Forma:", matriz.shape)  # filas x columnas
print("Elemento fila 0, columna 1:", matriz[0, 1])
print("Toda la fila 1:", matriz[1, :])
print("Toda la columna 2:", matriz[:, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma: (3, 3)
Elemento fila 0, columna 1: 2
Toda la fila 1: [4 5 6]
Toda la columna 2: [3 6 9]
