# Día 5 — Arrays 2D: trabajando con tablas de datos

Un array 2D es como una tabla con filas y columnas.
Es la base de cómo pandas maneja los datos después.

In [25]:
import numpy as np

# Imagina que esto es una tabla de 4 vendedores
# con sus ventas durante 3 meses
ventas = np.array([
    [150, 200, 180],  # vendedor 1
    [300, 250, 310],  # vendedor 2
    [100, 130, 90],   # vendedor 3
    [220, 195, 240]   # vendedor 4
])

print(ventas)
print("Forma:", ventas.shape)

[[150 200 180]
 [300 250 310]
 [100 130  90]
 [220 195 240]]
Forma: (4, 3)


## Ejercicio — Análisis de ventas por vendedor y mes

Usando el array de ventas de 4 vendedores y 3 meses:

1. ¿Cuál fue el total de ventas de cada vendedor? (suma por fila)
2. ¿Cuál fue el total de ventas de cada mes? (suma por columna)
3. ¿Cuál fue el promedio de ventas de cada vendedor?
4. ¿Qué vendedor tuvo el mejor total?
5. ¿Qué mes fue el mejor?

In [56]:
venta_total_vendedor= np.sum(ventas, axis=1)
venta_total_max=0
print("Ventas totales por vendedor:")
for x in range(len(venta_total_vendedor)):
    print("Vendedor ",x+1,": ",venta_total_vendedor[x])
venta_total_mes= np.sum(ventas,axis=0)
print("Ventas totales por mes:")
for x in range(len(venta_total_mes)):
    print("Mes ", x+1,": ", venta_total_mes[x])
venta_prom_vendedor= np.mean(ventas, axis=1)
print("Promedio de ventas de cada vendedor:")
for x in range(len(venta_prom_vendedor)):
    print("Vendedor ",x+1,": ",venta_prom_vendedor[x])

print("el mejor vendedor es el vendedor ",np.argmax(venta_total_vendedor)+ 1, "con una venta total de: ",venta_total_vendedor[np.argmax(venta_total_vendedor)])
print("donde hubo mejor venta es el mes ",np.argmax(venta_total_mes)+1, "con una venta total de: ",venta_total_mes[np.argmax(venta_total_mes)])

Ventas totales por vendedor:
Vendedor  1 :  530
Vendedor  2 :  860
Vendedor  3 :  320
Vendedor  4 :  655
Ventas totales por mes:
Mes  1 :  770
Mes  2 :  775
Mes  3 :  820
Promedio de ventas de cada vendedor:
Vendedor  1 :  176.66666666666666
Vendedor  2 :  286.6666666666667
Vendedor  3 :  106.66666666666667
Vendedor  4 :  218.33333333333334
el mejor vendedor es el vendedor  2 con una venta total de:  860
donde hubo mejor venta es el mes  3 con una venta total de:  820


NO SE PUEDE NO USAR FOR SI NECESITAMOS ETIQUETAS COMO VENDEDOR 1,2,3,4 (se necesita pandas, usar mas tarde)
